services:
  redis:
    image: redis:alpine
    command:
      [
        "redis-server",
        "--requirepass",
        "redispassword",
        "--tls-port",
        "6379",
        "--port",
        "0",
        "--tls-cert-file",
        "/cert/cert.crt",
        "--tls-key-file",
        "/cert/cert.key",
        "--tls-ca-cert-file",
        "/cert/ca.crt",
      ]
    ports:
      - "6379:6379"
    volumes:
      - ./config/cert:/cert
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    volumes:
      - ./config/cert:/home/.minio/certs
  postgres:
    image: postgres:alpine
    command:
      [
        "-c",
        "ssl=on",
        "-c",
        "ssl_cert_file=/cert/cert.crt",
        "-c",
        "ssl_key_file=/cert/cert.key",
        "-c",
        "ssl_ca_file=/cert/ca.crt",
        "-c",
        "hba_file=/etc/postgresql/pg_hba.conf",
      ]
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./config/cert:/cert
      - ./config/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf
